### ISSUE TITLE
Add hyperlinked (or hover-over) descriptions of what different columns mean

### ISSUE THREAD

**Issue by jchodera** [choderalab/fah-xchem#105]
We should provide more detail on what the different quantities we compute mean to make it easier to interpret the results, especially for the leaderboard.

**Comment by jchodera** [comment]
This should also be done for the forward/reverse work distributions and free energy estimates as a function of GEN

**Comment by jchodera** [comment]
Also:
> Sprint 5 science dashboard: I don't understand the difference between the graph and the table: In the graph the best molecule has free energy relative to reference of about -6.5kcal/mol, but in the table -16.8kcal/mol. If I remember right, in the last sprint (4) the figures were identical. Bug or Feature? (edited)

**Comment by glass-w** [comment]
I think something like a [popover](https://getbootstrap.com/docs/3.4/javascript/#popovers) would be good for the column headers (e.g. with an "i" icon next to the column header) and a hyperlink for a more in-depth description

**Comment by glass-w** [comment]
closed in #116
