### ISSUE TITLE
Push snapshots to fragalysis

### ISSUE THREAD

**Issue by jchodera** [choderalab/fah-xchem#113]
We should use the [Fragalysis spec](https://discuss.postera.ai/t/providing-computed-poses-for-others-to-look-at/1155/8?u=johnchodera) to automatically push  bound poses to fragalysis, in ranked order, with their predicted pIC50 annotations. 

There is now code that can be used to do this here:
https://github.com/xchem/fragalysis-api/blob/master/fragalysis_api/xcextracter/computed_set_update.py

**Comment by glass-w** [comment]
Closed in #119
