### ISSUE TITLE
Don't regenerate plots or snapshots that don't need to be updated

### ISSUE THREAD

**Issue by jchodera** [choderalab/fah-xchem#124]
It currently takes ~40 min to regenerate snapshots and ~40 min to generate plots for Sprint 5. 

If we have received no new data for a RUN since the last analysis pass, we shouldn't need to regenerate a snapshot and can skip over it.

Perhaps we could record how much data we had processed in the last pass in the JSON file and note to skip over these steps for that RUN if this has not changed.

**Comment by dotsdl** [comment]
See #136 for a proposed solution to this.

**Comment by dotsdl** [comment]
@jchodera even with the changes from #136, do we still see very slow behavior in production when we hit [`fah_xchem.analysis.generate_representative_snapshots`](https://github.com/choderalab/fah-xchem/blob/7933e2606add5a69de1b307040b28701dd455503/fah_xchem/analysis/__init__.py#L195)? 

I want to verify that skipping generation of representative snapshots that are already present is insufficient performance-wise for us, which is what #136 should be doing for us.

**Comment by dotsdl** [comment]
Closing as resolved; please re-open if this issue persists are arises again.
