### ISSUE TITLE
Production conda environment removes and installs older versions of multiple libraries when it hits pip dependencies

### ISSUE THREAD

**Issue by dotsdl** [choderalab/fah-xchem#156]
When installing the production environment with `conda env create -f environment.yml`, we get at the end:

```
Installing collected packages: numpy, threadpoolctl, scipy, joblib, scikit-learn, sklearn, setuptools, pypdb, pybind11, psutil, biopython, pandda-gemmi, gemmi, fragalysis-api, arsenic
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.1
    Uninstalling scipy-1.7.1:
      Successfully uninstalled scipy-1.7.1
  Attempting uninstall: joblib
    Found existing installation: joblib 1.0.1
    Uninstalling joblib-1.0.1:
      Successfully uninstalled joblib-1.0.1
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.0.4
    Uninstalling setuptools-58.0.4:
      Successfully uninstalled setuptools-58.0.4
  Attempting uninstall: psutil
    Found existing installation: psutil 5.8.0
    Uninstalling psutil-5.8.0:
      Successfully uninstalled psutil-5.8.0
Successfully installed arsenic-0.1.0 biopython-1.79 fragalysis-api-0.0.2.2 gemmi-0.4.2 joblib-0.17.0 numpy-1.19.5 pandda-gemmi-0.0.1 psutil-5.7.3 pybind11-2.7.1 pypdb-2.0 scikit-learn-0.23.2 scipy-1.5.4 setuptools-50.3.2 sklearn-0.0 threadpoolctl-2.2.0
```

This appears to be due to [pandda_gemmi](https://github.com/xchem/pandda_gemmi/blob/master/requirements.txt). Its `requirements.txt` is used to encode its `setup.py` `install_requires`, and it uses equality, effectively pinning versions of these libraries.

**Comment by dotsdl** [comment]
@TJGorrie is there a reason for the equality pins in [this file](https://github.com/xchem/pandda_gemmi/blob/master/requirements.txt)? If not, could you use minimum version ranges (e.g. `numpy>=1.19.4`) instead? I would make an issue on `pandda_gemmi`, but it looks like issues are disabled on that repo?

**Comment by TJGorrie** [comment]
Hi @dotsdl I'll ask the original developer of pandda gemmi why pandda_gemmi is pinned with ~= instead of a >=. In the meantime I will also change the requirements in the xchem/pandda_gemmi repo to use >=.

I will also raise an issue on original repo (https://github.com/ConorFWild/pandda_gemmi)

**Comment by TJGorrie** [comment]
Although, my only immediate thought is that Numpy 1.19.x is the last version that 'supports' Python3.6

**Comment by TJGorrie** [comment]
Scratch that, the ~= bindings are my result of me dumping the environment that I was developing fragalysis-api on and where I install pandda_gemmi in originally so there isn't a reason why it is that specific version and all the requirements could be replaced with later versions.

**Comment by dotsdl** [comment]
@TJGorrie thank you so much! Apologies for the delay from me; will give this a shot now to see if we're no longer impacted by the issue!

**Comment by dotsdl** [comment]
Thanks @TJGorrie! Can you also remove `sklearn`? That's not a maintained package on PyPI. Otherwise works much better!

**Comment by TJGorrie** [comment]
Not too sure about removing sklearn as it is technically used by pandda_gemmi - I will double check with the original author though and make a note about how best to reliably install it so future pip installs won't fail.
